// Answers for Codle, the Wordle-style game in the Games folder. One is picked at random each round, and its `hint`
// is shown when the round ends. Rules (checked by content.test.ts): exactly 5 letters A–Z, uppercase, no duplicates.
// Add as many as you like — keep them about mobile development, CS or the club.

export type CodleWord = { word: string; hint: string };

export const codleWords: CodleWord[] = [
  // Mobile + UI
  { word: "SWIFT", hint: "Apple's language for iOS, iPadOS and watchOS apps." },
  { word: "XCODE", hint: "Apple's IDE for building and shipping iOS apps." },
  { word: "REACT", hint: "A UI library for the web; React Native uses it to build mobile apps." },
  { word: "IONIC", hint: "A framework for building mobile apps with web technologies." },
  { word: "UNITY", hint: "A game engine that ships to iOS and Android (and much more)." },
  { word: "SEGUE", hint: "A transition from one screen to another in an iOS storyboard." },
  { word: "SWIPE", hint: "Dragging a finger across the screen — the gesture behind this site's lock screen." },
  { word: "TOUCH", hint: "The main way people talk to a phone." },
  { word: "PINCH", hint: "The two-finger gesture used to zoom." },
  { word: "PHONE", hint: "The device we build for (and the one this site pretends to be)." },
  { word: "WATCH", hint: "Apple Watch and Wear OS apps live on the wrist." },
  { word: "PIXEL", hint: "The smallest dot on a screen — and the name of Google's phones." },
  { word: "EMOJI", hint: "Tiny pictures that are really just Unicode characters." },
  { word: "BADGE", hint: "The little red number on an app icon." },
  { word: "ALERT", hint: "A pop-up dialog that asks the user to decide something." },
  { word: "MODAL", hint: "A screen presented on top of another, which you must dismiss to go back." },
  { word: "THEME", hint: "A set of colours and fonts — dark mode is one." },
  { word: "STORE", hint: "Where users get apps: the App Store or Google Play." },
  { word: "ALPHA", hint: "An early test version of an app, before the beta." },
  { word: "FRAME", hint: "One drawn image; 60 of them per second feels smooth." },
  { word: "LAYER", hint: "Views stack in layers; iOS draws them with Core Animation." },
  { word: "FOCUS", hint: "Which element receives keyboard input right now." },
  { word: "AUDIO", hint: "Sound in an app — the Music app here plays it through YouTube." },
  { word: "VIDEO", hint: "Moving pictures, usually streamed and decoded by the phone's hardware." },
  { word: "CLOUD", hint: "Someone else's computers that store your app's data." },
  { word: "LOGIN", hint: "The screen every app seems to start with." },
  { word: "OAUTH", hint: "The standard behind \"Sign in with Google\" and \"Sign in with Apple\"." },
  { word: "HTTPS", hint: "Encrypted web traffic; app stores expect apps to use it." },

  // React + JavaScript
  { word: "REDUX", hint: "A predictable state container often used with React." },
  { word: "STATE", hint: "The data that decides what the UI shows right now." },
  { word: "PROPS", hint: "The inputs a parent passes to a React component." },
  { word: "HOOKS", hint: "React functions like useState and useEffect." },
  { word: "ROUTE", hint: "A path to a screen — this site has /about, /exec and friends." },
  { word: "FETCH", hint: "The JavaScript function for making network requests." },
  { word: "ASYNC", hint: "Code that runs without blocking; pairs with await." },
  { word: "AWAIT", hint: "Pauses an async function until a promise settles." },
  { word: "CONST", hint: "Declares a binding that can't be reassigned." },
  { word: "YIELD", hint: "Hands a value out of a generator and pauses it." },
  { word: "SUPER", hint: "Calls the parent class's constructor or method." },
  { word: "CLASS", hint: "A blueprint for objects." },

  // Swift, Kotlin and other languages
  { word: "GUARD", hint: "Swift's early-exit statement: guard let x else { return }." },
  { word: "DEFER", hint: "Runs code when the current scope ends (Swift, Go)." },
  { word: "TUPLE", hint: "A fixed-size group of values, like (x, y)." },
  { word: "MACRO", hint: "Code that writes code at compile time — Swift has them too." },
  { word: "MONAD", hint: "The functional programming idea everyone explains differently." },
  { word: "PANIC", hint: "How Go and Rust say something went very, very wrong." },
  { word: "WHILE", hint: "A loop that runs as long as its condition is true." },
  { word: "BREAK", hint: "Jumps out of the nearest loop." },
  { word: "PRINT", hint: "The oldest debugger in the world." },
  { word: "INPUT", hint: "Data coming into a program." },
  { word: "LOGIC", hint: "Boolean AND, OR, NOT — the core of every if statement." },

  // Data structures + algorithms
  { word: "ARRAY", hint: "Items stored side by side, reached by index." },
  { word: "STACK", hint: "Last in, first out — like the call stack." },
  { word: "QUEUE", hint: "First in, first out — like the line at a food truck." },
  { word: "GRAPH", hint: "Nodes joined by edges; maps and social networks are graphs." },
  { word: "FLOAT", hint: "A number with a decimal point (and some rounding surprises)." },
  { word: "SLICE", hint: "A view into part of an array or string." },
  { word: "INDEX", hint: "An item's position — it starts at 0." },
  { word: "TOKEN", hint: "The smallest meaningful piece of text for a parser (or an LLM)." },
  { word: "PARSE", hint: "Turn raw text into structured data." },
  { word: "REGEX", hint: "A pattern language for matching text; powerful and hard to read." },
  { word: "ASCII", hint: "The classic 128-character text encoding." },

  // Systems + tools
  { word: "LINUX", hint: "The open-source kernel under Android." },
  { word: "POSIX", hint: "The standard that keeps Unix-like systems compatible." },
  { word: "SHELL", hint: "The command-line program that runs your commands." },
  { word: "EMACS", hint: "An editor so extensible it's nearly an OS." },
  { word: "CHMOD", hint: "The Unix command that changes file permissions." },
  { word: "CACHE", hint: "A fast copy kept close by, so you don't fetch it again." },
  { word: "PROXY", hint: "A server that forwards requests on someone else's behalf." },
  { word: "MUTEX", hint: "A lock that lets only one thread in at a time." },
  { word: "SPAWN", hint: "Start a new process or thread." },
  { word: "EPOCH", hint: "Jan 1, 1970 in Unix time — or one full pass over ML training data." },
  { word: "NGINX", hint: "A popular web server and reverse proxy." },

  // Data, back ends + ML
  { word: "QUERY", hint: "A question you ask a database." },
  { word: "TABLE", hint: "Rows and columns in a relational database." },
  { word: "FIELD", hint: "One named value in a record, form or struct." },
  { word: "MONGO", hint: "MongoDB, a document database." },
  { word: "REDIS", hint: "An in-memory key–value store, often used as a cache." },
  { word: "KAFKA", hint: "A platform for streaming events between services." },
  { word: "SPARK", hint: "Apache Spark, for processing big data on clusters." },
  { word: "FLASK", hint: "A small Python web framework." },
  { word: "RAILS", hint: "Ruby on Rails, the framework behind many early startups." },
  { word: "NUMPY", hint: "Python's library for fast arrays and math." },
  { word: "TORCH", hint: "PyTorch, a machine learning library." },
  { word: "BATCH", hint: "A group of items processed together." },
  { word: "LABEL", hint: "The right answer attached to a training example." },
  { word: "AGENT", hint: "An AI model that uses tools to finish a task step by step." },

  // Debugging, git + teamwork
  { word: "DEBUG", hint: "Finding out why it doesn't work." },
  { word: "ERROR", hint: "Something went wrong — read the message!" },
  { word: "CRASH", hint: "When an app suddenly quits; crash reports tell you why." },
  { word: "BUILD", hint: "Turning source code into an app you can run." },
  { word: "CLONE", hint: "Copy a git repository to your computer." },
  { word: "MERGE", hint: "Combine one branch into another." },
  { word: "STASH", hint: "git stash: put your changes aside for a moment." },
  { word: "PATCH", hint: "A small change or fix to code." },
  { word: "ISSUE", hint: "A GitHub ticket for a bug or a feature." },
  { word: "AGILE", hint: "Building in small steps and adjusting as you go." },
  { word: "SCRUM", hint: "An agile way of working in sprints with daily stand-ups." },
  { word: "PITCH", hint: "Presenting your app idea to the team." },
  { word: "CODER", hint: "You, probably." },
];
